site_name: Carl-bot Documentation
theme: 
  name: 'material'
  logo: 'images/googleturtle.svg'
  favicon:
    'images/favicon.ico'
  features:
    - tabs
    - instant
  palette:
    scheme: preference
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  
repo_name: 'carlbot-docs'
repo_url: 'https://github.com/CarlGroth/carlbot-docs'

extra:
  social:
    - icon: 'fontawesome/solid/globe-americas'
      link: 'https://carl.gg'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/CarlGroth'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/Carlgrrr'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all

google_analytics:
  - 'UA-126357432-1'
  - 'auto'

copyright: 'Copyright &copy; 2018 - 2020 Carl (admin@carl.gg)'
https://www.typescriptlang.org/play?filetype=js&useJavaScript=truee=4#code/GYVwdgBAtghglmAFASggbwLACgK4G4wA2EA1gPYAuhCEAvBAESC8G4EJ7D2uEADgE4JVJyVBMmwBfDhAD0UgBYUKXAFwyAxkQBGAUxg8yADwB0AczgVZIDYbhkpXSlrAU4RALRQyYLQE8ZUiAAq3lxaAMqqfFwUELIwAM4QeFo83hB8qrIQAFKhACJkqhBxIFz2PBQANBDAZDwQMBCElBBkwBDqcVpx2DIQ3mQg7TCQWkmQcSRwXNAwk2DGfQN1wHCEXRCGFAnDACYQAFYgcdFHWtl5BT3+w2CUMM6eCRRk7Tw6FGcN6Zk7o1pNXCgjmijjwcD0YCBTkMVyuEAAgud8oVVGQoFDonBttAQIRnK5qF52miMRAAO6yOAZIoUXRbclmWRwihkl7HXQJBDHHR7VotLwwrA9ABUgUpnOxtx4sGIqPRwIgwqkItFAXFECx9SRBWJ8qciuVQqwvRyyN1GIS2jlnwUMAyWj2zwg5jOqianWO2RgBHCkQocNRvwg2iaZI1FEF2FRYE9UG8ADVdC4NGs6IwABJwBgAbmwcIAkm1+oNZGQknUy8loAmkzAU1oqsWhuMtGdzPdwzF4s7ZFpmVp9NFgHooBqY3Agy7tSiSQr7rT7TtI8b-KadXKLfU3lqyTBUk7eGWJ23gmcEDVpfcbJBnnCgiFfVNortFiA6g6zLU4oYIAAZLQUAA5Ak7LlAy5j1CM8SpJ4fYrkUAHOPMWoEHwdZrMBzqns6LwNBoICrBQrg0BQp7Lr0ABitT1IQxB8i6nQQAOMBQFwaxxI2AzNjElYVuWPZnGALENnCL6eAJEBeIOjQIG2KTknwHwQAA2sxrFrAAuj+TqdG2vaiSAzyuHKbEAWcZBRNe355sawqigAAqRIToGAIBQNoPBiAa2CodWABybkebmRq9AAmlx6gtp8tEtG0U7FKUtQfI6MDGJyN69l2YA7BoZBkCQSiwvB8iKHEKhSGSlWbKecQRE+hDDMYhi1MYUg7AUcRyLsuX5VITlaMZvaqHMxiuPs3rxHVUSuCs7GGPIUCEAAxAlZTJWNcTtaoNm9OmZBkn8PBVAdgExRQ8nGC85h6CAxiZHEaLmXFmUeNuG7iWppndMVyRaD+4WDJFNEPcSXCpAAZNw8RKcMqSfex1QjhJsTZT1JBwvwLy9m85H+PmrFJQgCxTv1CQXl6PpTdE0YrMYb5XuJs1dIVIV2RAjnYWgGoE+UiAMAdGhcHaJAMMghgAMKeLTEBeUqUaPNTUtwAs9BoGIwVwuLbxXshDQmWs+hYc5TpvK4pxjjMYCpGxdrMztdkcA5-W-G0aAAPIaPsWiqBQXkAKqdHUrhagHVZ2qi4D+jgDmHiE5SpGgxx8PMXk7FiNveH5wkQMHU5CUCECnI6bKlmGU6nDwjvs7HySkS5gXJF5E451q4BwAAjiAZ47I7hp3r2kDm2YwapG8wC-WAqhExJztaMAmH51oLMquz-XoBAod1LLhrRp6FdpmrGvwWqv2YVO95hFTupC849ZjoSJ7OXEpblCjOwVHCFJUpkTZA+b5O5QgmvF8s9gDL1sk7TmXN9peB4EoDegcqiL3gUnaeYht7yxjNEN4D03yqC0EfKQbMOYhBdugNAMDkjwM3kg4SKDzpE3QRAAASl0JY+DvKs0gc5NArDcE8HwRgrAu9oiUGxnw9hBCdr+FyN7BqycFgNGdtUcAPtrzgKIcKKu8Idg7CeKySSDceBPDIMYAC2Mq72SFjwFi9d3KNy1Cfao4JPSuXsZXaO1ddC2LQG4jyXkNBijOJ0aMew-HJEsW8Cgb4Yx2P8b3bAoBJ4PEgDAXRARWQBXcXERAMAqgaFQJgHAaQAIxK1AAamDMFCQIV-AA24ubDwno+QX0fFEM+2FnhkEIBxGSJAzht0eBo4ha80CIFQchAAPsGPKaxhjICEWsaIEzjBux4AAIVmToSA9AGA5mwCstZmzunbLTMAIgnRCH+AAKKDkcGnZCxgmgaAuRbNchRNQNFemeMAeBulJD2IefBcRvq9C-tSX+wwEI-IkvGUIEBJZBi2mVIqvQSpcDKmoMgvxDBgmKBc6JacyCGDlG1DqUhbi-H2J1VkPARquDJIyMaE1ap+iWgAfSeWQF5hBXCoWTOxVwuxXD9UGt7Ea0iES6Onu880wITGvmWKolJEodwIAZQgOEcQzAgAZmAbMr4IBmOiNoBQVYumEkUdlIoLx2o0WIMWDxvR4QAAV8zEhjG5ZI34gA
